More correct monster names
CaravelGames/drod pull request #16
Opened 2018-06-11 16:31 UTC by Hypexion

Part two of my crusade to make names more consistent. This PR covers Fegundo, Seep, Rock Golems and Rock Giants.

This doesn't cover any of the snakes, or engineers, because they're all internally consistent. Also, the snake file names make it pretty obvious what lives inside them.

2020-09-22 17:05 UTC, mrimer commented
@Hypexion , would you please rebase this PR?

2020-09-23 00:44 UTC, mrimer requested changes
Looks good!
Thank you for the good neighborly effort to keep the codebase clean.
I suggested minor tweaks.

The PR says that Texts/Speech.uni has a conflict.  Would you please resolve this, and then I'll merge.  (Sorry, I don't know of an easy way to do that.  Do you have a utility that can perform a readable diff on the .uni files?)

2020-09-23 00:44 UTC, mrimer commented on DRODLib/RockGiant.cpp
> +//Splitter.cpp
Remove this comment.

2020-09-23 00:44 UTC, mrimer commented on DRODLib/RockGiant.h
> +//Splitter.h
Clean up this comment.

2020-09-23 00:51 UTC, mrimer commented
Oh, and may I request to update the DRODLib.2019.vcxproj project file (etc) with the new file names?

2020-09-23 09:04 UTC, Hypexion commented
@mrimer I've updated the VS2019 project file, fixed up the comments and resolved the conflict.

It appears that most Git clients don't recognise the UCS2 encoding the uni files use as text, which is certainly a decision they are allowed to make. Luckily, TortioseGit does treat them as text, allowing you merge and diff them normally. Changing the encoding might help, but since a free tool exists that works, it's probably safer to leave it.

2020-09-23 14:39 UTC, mrimer approved these changes

2020-09-23 14:54 UTC, merged