Additional NPC behaviors
CaravelGames/drod pull request #244
Opened 2020-10-27 22:39 UTC by Hypexion

A few more behaviors, which probably means all the simple to implement ones are done.

**Activate Pressure Plates** is fairly self-explanatory, I think. It replaces the current type check in `CCharacter::CanPressPressurePlates()` with a behavior flag check. Flying and Seep characters get this behavior by default replicate the old logic. This also required a small change to `CDbRoom::ResetUnloadedPressurePlates()` - it now directly checks if a monster can press plates to determine if it will hold down a plate, rather than checking for flight or being a Seep.

**Push Monsters** exists primarily as a hack to maintain previous game logic. Construct-based characters have the ability to push monsters, but not objects. So to avoid any potenial issues, I've split the behaviors in two. This requires a small change to `CMonster`, to add a `CanPushMonsters()` method, and to `CMonster::Move()` to use it when checking if monsters can push another monster. For all predefined monsters, `CanPushMonsters()` calls `CanPushObjects()` to ensure the current logic is maintained.

**Push to Fall Immunity** stops a monster from being pushed into water or pit tiles if that would kill it. This requires a character-specific `CanPushOntoOTileAt()` method to check if a push is allowed, and a change in `CDbRoom::CanPushMonster()`. (One could argue that some refactoring could be done so that monsters deal with what tiles they can be pushed onto instead of the room.)

(Currently a draft PR until I write up the help file content for these new behaviors)

2020-10-28 17:43 UTC, mrimer commented on Data/Help/1/script.html
> +	<li><a name="imp-pushable-by-body"><b>Pushable by body</b></a>: Makes the NPC pushable by the body of the player, mimics, constructs and charatcers with the <a href="#beh-push-monsters">Push Monster
charatcers -> characters

2020-10-28 17:43 UTC, mrimer reviewed
I like these changes!

2020-10-28 23:59 UTC, mrimer commented
Thanks for the fix.
Is this PR ready to merge?

2020-10-29 00:00 UTC, mrimer approved these changes

2020-10-29 07:22 UTC, EvidentlyCube requested changes
Just one thing in a comment - any chance you could also add a few tests to cover at least a bunch of generic cases for this?

2020-10-29 07:22 UTC, EvidentlyCube commented on DRODLib/Character.cpp
> +	// If the character is immune to "fatal pushes", only allow it to pushed
to pushed -> to be pushed ?

2020-11-01 21:37 UTC, EvidentlyCube approved these changes

2020-11-02 06:13 UTC, merged