Puzzle mode options
CaravelGames/drod pull request #303
Opened 2020-11-08 00:10 UTC by EvidentlyCube

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44932)

Note: I have not moved any texts to MIDs file yet. I'll do it tomorrow, but in the meantime feel free to review the rest of the code.

2020-11-08 11:53 UTC, EvidentlyCube commented
I consider this finished.

2020-11-08 16:35 UTC, mrimer requested changes
Puzzle mode fans now have everything their heart desires!
Thank you.  Looks great.
In noted a few minor changes to make.

2020-11-08 16:35 UTC, mrimer commented on .gitignore
> +!drod/drod.2019.vcxproj.filters
Thanks for catching these.

2020-11-08 16:35 UTC, mrimer commented on DROD/GameScreen.cpp
> +//Pop up a dialog box that contains a log of the speech played in the current room.
Need to update comment.

2020-11-08 16:35 UTC, mrimer commented on DROD/RoomWidget.cpp
> +		TogglePuzzleMode();
Please comment why this needs to be called twice.

2020-11-08 16:35 UTC, mrimer commented on FrontEndLib/LabelWidget.h
> +static const UINT CY_LABEL_FONT_HEADER = 30;
Thank you for refactoring these magic numbers.

2020-11-08 16:35 UTC, mrimer commented on drod/PuzzleModeOptions.h
> +	PuzzleModeOptions() {
For the default constructor, lets use the standard construction variable initialization idiom, i.e.,
`Constructor() : var1(val), var2(val), ... { }`

2020-11-08 21:18 UTC, EvidentlyCube commented
PR updated!

2020-11-09 18:11 UTC, mrimer approved these changes
Thanks for the revisions!

2020-11-09 18:11 UTC, merged